### ISSUE TITLE
Enable all menus

### ISSUE THREAD

**Issue by tacman** [survos/rapidpro#1]
We're missing menus for "Learn", and "Pricing".

![image](https://cloud.githubusercontent.com/assets/619585/17118485/c74b7cca-528e-11e6-9a23-848fc81556bb.png)

**Comment by wis-auralov** [comment]
I looked at modules structure and [url](https://github.com/survos/rapidpro/blob/master/temba/urls.py) configuration. [Temba](https://github.com/survos/rapidpro/tree/master/temba) directory contains all system modules.
Original RapidPro repository doesn't contain "Learn" and "Pricing" modules. We cannot enable them as they are not written. I attempted to enter a public TextIt repository, it [doesn’t exist](https://www.google.ru/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#newwindow=1&q=TextIt+repository). TextIt is a private fork of RapidPro, they wrote these modules for yourself. If you need modules "Learn" and "Pricing", I can write similar.
